name: Build public assets

on:
  push:
    branches:
      - development

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - run: yarn build

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Commit public assets
        run: |
          git config --global user.name 'Marcel Ulbrich'
          git config --global user.email 'ulbrich-media@users.noreply.github.com'
          git add -A
          git commit -m "build: public assets"
          git push