name: Build public assets

on:
  push:
    branches:
      - production
      - feature/build

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build
      - name: Commit report
        run: |
          git config --global user.name 'Marcel Ulbrich'
          git config --global user.email 'ulbrich-media@users.noreply.github.com'
          git commit -am "build: public assets"
          git push