name: "Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        default: ''
        required: true

jobs:

  audit:
    name: 'Audit'
    runs-on: ubuntu-20.04
    steps:
      - name: Check version
        run: |
          if ! [[ ${{ github.event.inputs.version }} =~ ^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

  build:
    name: 'Build'
    needs: audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: rm -rf .git .github node_modules
      - run: zip -r clubcms.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: clubcms
          path: ./clubcms.zip

  release:
    name: 'Release'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: create_changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: CHANGELOG.md
          skip-version-file: true
          skip-git-pull: true
          preset: 'conventionalcommits'
          fallback-version: ${{ github.event.inputs.version }}
          tag-prefix: ''
      - uses: actions/download-artifact@v3
        with:
          name: clubcms
          path: ./
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: ${{ steps.create_changelog.outputs.clean_changelog }}
          draft: false
          prerelease: true
      - run: echo "{steps.create_release.outputs.html_url}" >> $env:RELEASE_URL
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clubcms.zip
          asset_name: clubcms.zip
          asset_content_type: application/zip

  publishTER:
    name: Publish to TER
    needs: release
    runs-on: ubuntu-20.04
    env:
      TYPO3_EXTENSION_KEY: ${{ secrets.TYPO3_EXTENSION_KEY }}
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: clubcms
          path: ./
      - run: unzip clubcms.zip -d ..
      - run: rm clubcms.zip
      - run: ls -lah
      - run: cat ext_emconf.php

      - name: Get comment
        id: get-comment
        run: echo ::set-output name=comment::Automated release of version ${{ github.event.inputs.version }}. See changelog on GitHub - ${{ env.RELEASE_URL }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, mbstring, json, zip, curl

      - name: Install tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Publish to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --comment "${{ steps.get-comment.outputs.comment }}" ${{ github.event.inputs.version }}