name: "Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        default: ''
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: publicAssets
          path: Resources/Public

  release:
    name: 'Release'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: publicAssets
          path: Resources/Public
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: true
          body_path: ''