name: "Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        default: ''
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: rm -rf .git .github node_modules
      - run: zip -r clubcms.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: clubcms
          path: ./clubcms.zip

  release:
    name: 'Release'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: clubcms
          path: ./
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: true
          body_path: ''
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clubcms.zip
          asset_name: clubcms.zip
          asset_content_type: application/zip